services:
  - type: web
    name: wardsewa-web
    runtime: docker
    plan: free
    region: singapore
    healthCheckPath: /up
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_NAME
        value: WardSewa
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: base64:v4d2yXmQkZ6tO7pA9sL3wR1eY8uI0oP5aB2cE4gH6jM=
      - key: APP_URL
        value: https://wardsewa-web.onrender.com
      - key: APP_TIMEZONE
        value: Asia/Kathmandu
      - key: APP_LOCALE
        value: ne
      - key: APP_FALLBACK_LOCALE
        value: en
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: wardsewa-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: wardsewa-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: wardsewa-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: wardsewa-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: wardsewa-db
          property: password
      - key: RUN_MIGRATIONS
        value: "true"
      - key: SEED_DATABASE
        value: "true"
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_STORE
        value: database
      - key: FILESYSTEM_DISK
        value: public
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: KHALTI_PUBLIC_KEY
        value: test_public_key_dc74e0fd57cb46cd93832aee0a505b8e
      - key: KHALTI_SECRET_KEY
        value: test_secret_key_f59e8b7d18b24b9993e168c81884c55b
      - key: KHALTI_BASE_URL
        value: https://a.khalti.com/api/v2/
      - key: SMS_PROVIDER
        value: log
      - key: SMS_FROM
        value: WardSewa
      - key: SPARROW_SMS_TOKEN
        sync: false
      - key: AAKASH_SMS_TOKEN
        sync: false
      - key: TWILIO_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_FROM_NUMBER
        sync: false

databases:
  - name: wardsewa-db
    databaseName: wardsewa
    user: wardsewa_user
    plan: free
    region: singapore
